name: sports803_tv
description: Premium live sports and Live TV streaming app for Sports 803.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  google_mobile_ads: ^5.1.0
  webview_flutter: ^4.9.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
